### ISSUE TITLE
Smart-UPS 1400 RM XL

### ISSUE THREAD

**Issue by turnrye** [memhamwan/inventory#11]
# Vendor

Unkown

# Invoice Number

Unkown

# Ordered On

Unknown

# Manufacturer

APC

# Model

Smart-UPS 1400 RM XL

# Serial Number

QS0348113152

**Comment by turnrye** [comment]
> Self-Test Result: | Failed

Batteries need replacing

**Comment by seichold** [comment]
Options (that are easy to get)
1. Batteries with wiring harness: $135
https://www.amazon.com/UPSBatteryCenter-SU1400RMXLB3U-Compatible-Battery-Replacement/dp/B00YLBLGX4

2. Bare batteries $22 x 4 = 88
https://www.amazon.com/ExpertPower-EXP1280-12V8AH-Rechargeable-Battery/dp/B00KQX5EDO

I recommend the bare batteries if we have the wiring harness.

**Comment by turnrye** [comment]
Yeah, let's just do the bare batteries.

**Comment by seichold** [comment]
Purchase made. See attachment for invoice. Paid with personal credit card to be reimbursement by HAMWAN
![image](https://user-images.githubusercontent.com/29682333/61962355-e8f38100-af8e-11e9-8071-4315f1195833.png)

**Comment by turnrye** [comment]
Today I went the LEB and pulled the batteries from the machine. The tray has had a little damage that Ill need to repair. I did not have the proper batteries on hand, so I took the tray with me. I’ll be making a return visit next week. @seichold can we coordinate me picking these 4 up from you next week? I’ll be donating 3 of my own 1290 batteries + 1 1280 to make a complete tray of 8.

**Comment by turnrye** [comment]
@seichold ’s batteries here actually went to the UPS at LEB.

**Comment by turnrye** [comment]
New tracking issue https://gitlab.com/memhamwan/inventory/-/issues/11
