### ISSUE TITLE
Smart-UPS 3000XL

### ISSUE THREAD

**Issue by turnrye** [memhamwan/inventory#7]
# Vendor

Donated by Todd Via

# Invoice Number

Unknown

# Ordered On

2015-01-10

# Manufacturer

APC

# Model

SUM3000RMXL2U

# Serial Number

???

**Comment by turnrye** [comment]
As of today, the indicator is showing that the batteries need replacement.

**Comment by turnrye** [comment]
Hey @seichold can you help hunt down replacement batteries for this?

**Comment by seichold** [comment]
I recommend bare batteries for this. I have an example listing below. This is the recommended replacement brand, but we can likely find others cheaper. 

SP12-5.5HR $18.29 * 8 = 146.32
https://www.amazon.com/SP12-5-5HR-Volt-AmpH-Battery-Terminal/dp/B01E706VAQ/

**Comment by turnrye** [comment]
Let's do it.

**Comment by seichold** [comment]
Purchase made. See attachment for invoice. Paid with personal credit card to be reimbursement by HAMWAN

![image](https://user-images.githubusercontent.com/29682333/61962237-b5b0f200-af8e-11e9-93e8-6a3a0b295da5.png)

**Comment by turnrye** [comment]
I received these batteries from @seichold about two weeks ago, but unfortunately they are not the proper batteries. We need the 8ahr/9ahr batteries for this device.

Today I went the LEB and pulled the batteries from the machine. The tray has had a little damage that Ill need to repair. I did not have the proper batteries on hand, so I took the tray with me. I’ll be making a return visit next week. @seichold has 3x of the replacement batteries from #11 , I’m going to retrieve those from him and donate 5 of my own. Hopefully we’ll have the batteries back up next week.

Additionally, this UPS has a line card in it, but we dont have it IP accessible. We need to do a hard reset on this and get it back in our IP tracker + password tracker.

**Comment by turnrye** [comment]
Discussion on the batteries happened here: https://memhamwan.slack.com/archives/C02FH44BY/p1600128443011500

Replacement batteries were installed here: https://memhamwan.slack.com/archives/C02FH44BY/p1600473430001200

Discussion about the state of the battery array is here: https://memhamwan.slack.com/archives/C02FH44BY/p1600473953010700

**Comment by turnrye** [comment]
Since a battery tray was installed and this is back to its previous condition, I am removing the "need repair" label.

**Comment by turnrye** [comment]
https://gitlab.com/memhamwan/inventory/-/issues/7
